dist: xenial
language: python
python:
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  python: '3.7'
  provider: pypi
  user: mmEissen
  password:
    secure: cFiwwu17ocCK/9r+4yjozjyKJgWqXKWEACRkZQnn4ELjED8R5VdbfILkPVHe40qXUeQzwV86xx1RheUQtQeM6Mv9g/56eOf3iAkxq3IrknUV1EL5GWnLnT8V7xyfrF3X2CGEwBWzvDgf4d0avZzfb/dToBItqyOXAsu4/gDWrk5Yjuf3B7xH9hzuZorgP4GJCbJe+P4Z72yp4YbZXcxSCBDRQ6zWWxZFmZpP4hYg2fvzYLLTECW7H526iFwAsCZiA+xAqbn4GQhBDs00Ox0prjtKuR3OYNhFO75p4hBxk0NoTlEv/Dy01cuWjFqT/J/J7tPU7+lxGiuLoyjU4uhxgYt876BuC04XgbgBcm4VZzoVPef4TFMK3dYhRW7LxYNhteYg4OG5QToLYYqtCy1D0J2MljdONWfzWtSppEFxsSXKbhPpIyvWrZtQsMY8ysxUHkckT0Je6d66SRh4kN35NuVPvraPp6cY0N82syYfKOnm+Nw1+avvlXtDz2KbR3v4s9LdzWNCkU9qEn9iadmaTVrIby2wDNXVUKs/tJggejAvFNturmfBcFYeRYBlSDFYJqs1DZK+szoQz43WCiR7oxeZ0b9q3Qwsb3UhTOXi73LOo7TZeTIoP4wNxAFxenCuAIaw4lQDqCtVxRfDcQ1I0NTmVUeAsadhPHDFveokRhI=
  on:
    branch: master
